CREATE DATABASE FOOTBALL;
USE FOOTBALL;

CREATE TABLE MANAGERS(
managerID INT AUTO_INCREMENT NOT NULL,
managerName VARCHAR(100) NOT NULL,
email VARCHAR(100),
PRIMARY KEY (managerID)
);

CREATE TABLE SPONSORS(
sponsorID INT AUTO_INCREMENT NOT NULL,
sponsorName VARCHAR(100) NOT NULL,
country VARCHAR(100) NOT NULL,
sponsorType VARCHAR(100),
sponsorshipCost BIGINT,
PRIMARY KEY (sponsorID)
);

CREATE TABLE STADIUMS(
stadiumID INT AUTO_INCREMENT NOT NULL,
stadiumName VARCHAR(100) NOT NULL,
capacity INT,
PRIMARY KEY (stadiumID)
);

CREATE TABLE COACHES(
coachID INT AUTO_INCREMENT NOT NULL,
coachName VARCHAR(100) NOT NULL,
age INT,
country VARCHAR(100),
email VARCHAR(100),
numberOfChampionships INT,
PRIMARY KEY (coachID)
);

CREATE TABLE NATIONAL_LEAGUES(
nationalLeagueID INT AUTO_INCREMENT NOT NULL,
nationalLeagueName VARCHAR(100) NOT NULL,
country VARCHAR(100),
teamNumber INT,
sponsorID INT,
PRIMARY KEY (nationalLeagueID),
FOREIGN KEY (sponsorID) REFERENCES SPONSORS(sponsorID)
);

CREATE TABLE TEAMS(
teamID INT AUTO_INCREMENT NOT NULL,
teamName VARCHAR(100) NOT NULL,
city VARCHAR(100),
budget BIGINT,
PRIMARY KEY (teamID),
nationalLeagueID INT NOT NULL,
coachID INT NOT NULL,
FOREIGN KEY (nationalLeagueID) REFERENCES NATIONAL_LEAGUES(nationalLeagueID),
FOREIGN KEY (coachID) REFERENCES COACHES(coachID)
);

CREATE TABLE PLAYERS(
playerID INT AUTO_INCREMENT NOT NULL,
playerName VARCHAR(100) NOT NULL,
age INT,
position VARCHAR(100) NOT NULL,
country VARCHAR(100),
transferFee BIGINT,
PRIMARY KEY (playerID),
teamID INT,
managerID INT,
FOREIGN KEY (teamID) REFERENCES TEAMS(teamID),
FOREIGN KEY (managerID) REFERENCES MANAGERS(managerID)
);

CREATE TABLE TEAMS_AND_STADIUMS(
teamID INT NOT NULL,
stadiumID INT NOT NULL,
PRIMARY KEY (teamID, stadiumID),
FOREIGN KEY (teamID) REFERENCES TEAMS(teamID),
FOREIGN KEY (stadiumID) REFERENCES STADIUMS(stadiumID)
);

CREATE TABLE TEAMS_AND_SPONSORS(
teamID INT NOT NULL,
sponsorID INT NOT NULL,
PRIMARY KEY (teamID, sponsorID),
FOREIGN KEY (teamID) REFERENCES TEAMS(teamID),
FOREIGN KEY (sponsorID) REFERENCES SPONSORS(sponsorID)
);

CREATE TABLE PLAYERS_AND_STADIUMS(
playerID INT NOT NULL,
stadiumID INT NOT NULL,
PRIMARY KEY (playerID, stadiumID),
FOREIGN KEY (playerID) REFERENCES PLAYERS(playerID),
FOREIGN KEY (stadiumID) REFERENCES STADIUMS(stadiumID)
);

CREATE TABLE PLAYERS_AND_PLAYERS(
playerID1 INT NOT NULL,
playerID2 INT NOT NULL,
PRIMARY KEY (playerID1, playerID2),
FOREIGN KEY (playerID1) REFERENCES PLAYERS(playerID),
FOREIGN KEY (playerID2) REFERENCES PLAYERS(playerID),
CHECK (playerID1 <> playerID2)
);